# Generated by Django 6.0.7 on 2026-07-25 11:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Mobile number must be digit', regex='^\\d{11}$')])),
                ('gender', models.CharField(choices=[('0', 'Female'), ('1', 'Men')], default='0', max_length=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=8)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
