# Generated by Django 6.0.7 on 2026-07-27 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(blank=True, default=True, help_text='This object is active')),
                ('answer', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(upload_to='upload_practice/')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_answer', to='practice.practice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_answer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Practice Answer',
                'verbose_name_plural': 'Practices Answer',
            },
        ),
    ]
