# Generated by Django 6.0.7 on 2026-07-27 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_practiceanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practiceanswer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='practiceanswer',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='practiceanswer',
            name='updated_at',
        ),
    ]
